# Generated by Django 4.2.7 on 2024-06-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mode_teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mode', models.CharField(max_length=20, unique=True, verbose_name='mode_teaching')),
            ],
            options={
                'db_table': 'mode_of_teaching',
            },
        ),
        migrations.CreateModel(
            name='Teacher_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('experience', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('info_about_teacher', models.TextField(blank=True, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('other_specialities', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='profile_image')),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.contact_info')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.locations')),
                ('main_specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachers.specializations')),
                ('mode_teaching', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.mode_teaching')),
            ],
            options={
                'db_table': 'info_teacher',
                'ordering': ('id',),
            },
        ),
    ]
