# Generated by Django 4.2.7 on 2024-06-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_spec', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'specialization',
                'ordering': ['id'],
            },
        ),
    ]
